// La responsabilidad de este módulo es definir los tipos de acciones disponibles
const GET_DRIVERS = 'GET_DRIVERS';
const GET_DRIVER_BY_NAME = 'GET_DRIVER_BY_NAME';
const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
const GET_DRIVER_DETAIL = 'GET_DRIVER_DETAIL';
const GET_TEAMS = 'GET_TEAMS';
const POST_DRIVER = 'POST_DRIVER';
const FILTER_BY_TEAM = 'FILTER_BY_TEAM';
const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN';
const SORT = 'SORT';
const FILTER_BY_AGE = 'FILTER_BY_AGE';
//----------------------------------------------
export { GET_DRIVERS, GET_DRIVER_BY_NAME, CLEAR_SEARCH_RESULTS, GET_DRIVER_DETAIL, GET_TEAMS, 
    POST_DRIVER, FILTER_BY_TEAM, FILTER_BY_ORIGIN, SORT, FILTER_BY_AGE };